# ONLY FOR DEV
#

version: '2.2'

services:
  postgres:
    restart: always
    image: "postgres:12"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tb-node/postgres:/var/lib/postgresql/data