version: '2.2'

services:
  # add local postgres instance
  postgres:
    restart: always
    image: "postgres:11.6"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tb-node/postgres:/var/lib/postgresql/data
  # add dependencies on postgres container
  tb-core1:
    depends_on:
      - postgres
  tb-rule-engine1:
    depends_on:
      - postgres
